In [32]:
# Random
# used to generate numbers randomly
import numpy as np
ran_num = np.random.randint(0, 100)
print(f"Random Number :{ran_num}")

Random Number :94


In [47]:
# float values

ran_num = np.random.rand()
print(f"Random Number :{ran_num}")

Random Number :0.273633426143697


In [104]:
# generating a random array

# generate random numbers between 0 and 25 and 8 values
int_arr = np.random.randint(0, 25, 8)
print(f"Ramdom Integer :{int_arr}")

print("-" * 60)
# generate numbers between 0 and 1
flt_arr = np.random.rand(5)
print(f"Float Array :{flt_arr}")

print("-" * 60)
# generate a 2d array - shape(3, 4) with rand integers
res = np.random.randint(1, 25, (3, 4))
print(f"Array :\n{res}")


Ramdom Integer :[ 1  2  9  5  0  3  5 14]
------------------------------------------------------------
Float Array :[0.14481701 0.71809113 0.25023188 0.24731149 0.31533375]
------------------------------------------------------------
Array :
[[ 8  9 18  7]
 [17 11  9 12]
 [ 2 13 15 16]]


In [120]:
# choose random numbers from numpy array

arr1 = np.array([1, 2, 3, 4, 5])

ran_num = np.random.choice(arr1)

print(f"random choice :{ran_num}")

random choice :2
