In [9]:
import numpy as np

# dot
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

array1  = np.dot(arr1, arr2)      # 4 + 10 + 18
print(array1)

32


In [14]:
# inner function

arr1 = np.array([[1, 3], 
                [5, 7]])

arr2 = np.array([[2, 4],
                 [6, 8]])

print(f"arr1 :\n{arr1}")
print(f"arr2 :\n{arr2}")

print("-" * 60)
res = np.inner(arr1, arr2)
print(f"res :\n{res}")

"""
[1*2+3*4  1*6+3*8]
[5*2+7*4  5*6+7*8]
"""

arr1 :
[[1 3]
 [5 7]]
arr2 :
[[2 4]
 [6 8]]
------------------------------------------------------------
res :
[[14 30]
 [38 86]]


In [18]:
# Outer function

arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])
print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")

print("-" * 60)
res = np.outer(arr1, arr2)
print(f"results :\n{res}")

"""
[1*2  1*4  1*6]
[3*2  3*4  3*6]
[5*2  5*4  5*6]
"""

arr1 :[1 3 5]
arr2 :[2 4 6]
------------------------------------------------------------
results :
[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


In [20]:
# determinant
arr1 = np.array([[1, 3], 
                 [5, 7]])

res = np.linalg.det(arr1)

print(f"Determinant is :{res}")

# (1 * 7) - (5 * 3)

Determinant is :-7.999999999999998


In [22]:
# solve function
A = np.array([[2, 4], 
              [6, 8]])

# constant vector
B = np.array([5, 6])

res = np.linalg.solve(A, B)

print(res)

"""
2x + 4y = 5
6x + 8y = 6

"""

[-2.    2.25]


'\n2x + 4y = 5\n6x + 8y = 6\n\n'

In [24]:
# Inverse of a matrix

arr1 = np.array([[2, 4], 
                 [6, 8]])

print(f"arr1 :\n{arr1}")
print("-" * 60)

res = np.linalg.inv(arr1)
print(res)


arr1 :
[[2 4]
 [6 8]]
------------------------------------------------------------
[[-1.    0.5 ]
 [ 0.75 -0.25]]


In [27]:
# trace function

arr1 = np.array([[6, 3, 5],
                 [9, 2, 1], 
                 [7, 8, 4]])
print(f"arr1 :\n{arr1}")

res = np.trace(arr1)

print(f"res :{res}")

arr1 :
[[6 3 5]
 [9 2 1]
 [7 8 4]]
res :12
