In [5]:
import numpy as np

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])

print(f"arr1 :\n{arr1}")

np.save("myfile.npy", arr1)


arr1 :
[[1 2 3]
 [4 5 6]]


In [6]:
loaded_array = np.load("C:\\Users\\Kiran\\CDAC\\Day14\\myfile.npy")
print(loaded_array)

[[1 2 3]
 [4 5 6]]


In [11]:
# save to multiple files

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")

np.savez("myfile1.npz", file1 = arr1, file2 = arr2)

arr1 :[1 2 3 4 5]
arr2 :[ 6  7  8  9 10]


In [15]:
# load the data from multiple arrays
import numpy as np

load_data = np.load("C:\\Users\\Kiran\\CDAC\\Day14\\myfile1.npz")

arr1 = load_data['file1']
arr2 = load_data['file2']

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")


arr1 :[1 2 3 4 5]
arr2 :[ 6  7  8  9 10]
