In [3]:
import numpy as np

# list as an argument

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [5]:
# passing a tuple as argument

arr1 = np.array((10, 20, 30, 40, 50))

print(arr1)

[10 20 30 40 50]


In [7]:
# zero dimension array example

arr2 = np.array(25)

print(arr2)

25


In [9]:
# one dimension array

arr3 = np.array([1, 2, 3, 4, 5])

print(arr3)

[1 2 3 4 5]


In [12]:
# two dimension array

arr4 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
# three dimension array

arr5 = np.array([[[1, 2, 3], 
                  [4, 5, 6]], 
                  [[7, 8, 9],
                  [10, 11, 12]]])

print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
# print the dimension of a numpy array

ar1 = np.array(50)
print(ar1.ndim)

print("-" * 60)

ar2 = np.array([1, 2, 3, 4, 5])
print(ar2.ndim)

print("-" * 60)

ar3 = np.array([[1, 2, 3, 4], 
                [6, 7, 8, 9]])
print(ar3.ndim)

print("-" * 60)

ar4 = np.array([[[1, 2, 3], 
               [4, 5, 6]], 
              [[7, 8 , 9],
               [10, 11, 12]]])

print(ar4.ndim)


0
------------------------------------------------------------
1
------------------------------------------------------------
2
------------------------------------------------------------
3


In [27]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

print("Array Dimension :", arr.ndim)

[[[[[1 2 3 4]]]]]
Array Dimension : 5


In [34]:

arr1 = np.zeros((2, 3))

print(arr1)

print("-" * 60)

arr2 = np.zeros((2, 3, 4))

print(arr2)


[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [45]:
arr02 = np.full((2, 2), 5)
print(arr02)

arr03 = np.full

[[5 5]
 [5 5]]


In [47]:
arr1 = np.random.rand(2, 2)
print(arr1)

print("-" * 60)

arr2 = np.random.rand(2, 2, 2)
print(arr2)




[[0.04548247 0.35554407]
 [0.54376392 0.20978911]]
------------------------------------------------------------
[[[0.34148622 0.03423753]
  [0.83207928 0.95076233]]

 [[0.36940342 0.8415555 ]
  [0.90657846 0.49695036]]]
