In [5]:
import numpy as np


matrix1 = np.array([[1, 2], 
                    [3, 4]])
print(f"matrix :\n{matrix1}")

print("-" * 60)

# 3x3

matrix2 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(f"Matrix :\n{matrix2}")

matrix :
[[1 2]
 [3 4]]
------------------------------------------------------------
Matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# matrix Multiplication

mat1 = np.array([[1, 2], 
                 [3, 4]])
mat2 = np.array([[5, 6], 
                 [7, 8]])
print(f"Matrix1 :\n{mat1}")
print(f"Matrix2 :\n{mat2}")

res = np.dot(mat1, mat2)
print(f"Product of mat1 and mat2 :\n{res}")

Matrix1 :
[[1 2]
 [3 4]]
Matrix2 :
[[5 6]
 [7 8]]
Product of mat1 and mat2 :
[[19 22]
 [43 50]]


In [18]:
# Matrix Trasnpose

mat1 = np.array([[1, 2], 
                 [3, 4]])
mat2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])

print(f"matrix1 :\n{mat1}")
print(f"matrix2 :\n{mat2}")

print("-" * 60)
mat1_tran = np.transpose(mat1)
print(f"Matrix1 Transpose :\n{mat1_tran}")

print("-" * 60)
mat2_tran = np.transpose(mat2)
print(f"Matrix2 Transpose :\n{mat2_tran}")


matrix1 :
[[1 2]
 [3 4]]
matrix2 :
[[1 2 3]
 [4 5 6]]
------------------------------------------------------------
Matrix1 Transpose :
[[1 3]
 [2 4]]
------------------------------------------------------------
Matrix2 Transpose :
[[1 4]
 [2 5]
 [3 6]]


In [22]:
# inverse

mat1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

print(f"Matrix :\n{mat1}")

mat1_inv = np.linalg.inv(mat1)
print(f"Inverse of mat1 :\n{mat1_inv}")

Matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Inverse of mat1 :
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [30]:
# determinent

mat1 = np.array([[1, 2], 
                 [3, 4]])
print(f"Matrix1 :\n{mat1}")

res_det = np.linalg.det(mat1)
print(f"Determinant :{res_det}")
      
print("-" * 60)
mat2 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])
print(f"Matrix2 :\n{mat2}")
res_det1 = np.linalg.det(mat2)

print(f"Determinant mat2 :{res_det1}")



Matrix1 :
[[1 2]
 [3 4]]
Determinant :-2.0000000000000004
------------------------------------------------------------
Matrix2 :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant mat2 :-9.51619735392994e-16


In [31]:
# flatten

mat1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])

print(f"matrix1 :\n{mat1}")
res = mat1.flatten()

print(res)


matrix1 :
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
