In [5]:
import numpy as np

# create and array
array1 = np.array([2, 4, 6])

print(array1.dtype)
print(array1.ndim)

print(array1)

int32
1
[2 4 6]


In [8]:
int_array = np.array([-2, -1, 0, 1, 2])

print(int_array.dtype)
print(int_array.ndim)
print(int_array)

int32
1
[-2 -1  0  1  2]


In [11]:
flt_array = np.array([0.1, 0.2, 0.3])

print(flt_array.dtype)
print(flt_array.ndim)
print(flt_array)

float64
1
[0.1 0.2 0.3]


In [14]:
comp_array = np.array([1+2j, 2+3j, 3+4j])

print(comp_array.dtype)
print(comp_array.ndim)
print(comp_array)

complex128
1
[1.+2.j 2.+3.j 3.+4.j]


In [18]:
# add the datatype when creating an array

arr1 = np.array([1, 2, 3, 4], dtype='int32')

print(arr1)
print(arr1.dtype)

[1 2 3 4]
int32


In [23]:
# 8 bit integer
arr1 = np.array([1, 3, 7], dtype="int8")

# 16 bit unsigned integer
arr2 = np.array([2, 4, 6], dtype='uint16')

# float 32 bit
arr3 = np.array([2.1, 3.2, 4.3, 5.4], dtype="float32")

# 64 bit complex
arr4 = np.array([1-2j, 2-3j, 3-4j], dtype="complex64")

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)




int8
uint16
float32
complex64


In [29]:
# converting it into different data types

int_arr = np.array([1, 2, 3, 4, 5]) 

print(int_arr)
print(int_arr.dtype)


print("-" * 60)
# convert it into float

flt_arr = int_arr.astype('float')

print(flt_arr)
print(flt_arr.dtype)


[1 2 3 4 5]
int32
------------------------------------------------------------
[1. 2. 3. 4. 5.]
float64
