In [7]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(f"Array1 :{arr1}")

n = 10
result =arr1 + n

print(result)

Array1 :[1 2 3 4 5]
[11 12 13 14 15]


In [18]:
# sum 

arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])
print(f"arr1 :\n{arr1}")

arr2 = np.array([[0, 1, 2],
                [0, 1, 2]])
print(f"arr2 :\n{arr2}")

result = arr1 + arr2

print(f"result :\n{result}")

arr1 :
[[1 2 3]
 [4 5 6]]
arr2 :
[[0 1 2]
 [0 1 2]]
result :
[[1 3 5]
 [4 6 8]]


In [28]:
import time

arr1 = np.array([1, 2, 3, 4, 5, 6,7, 8, 9, 10])

print(f"arr1 :{arr1}")

st = time.time()

# Loop to iterate
for i in range(len(arr1)):
    for j in range(10000):
        arr1[i] += (j ** 2)
et = time.time()

print(f"arr1 :{arr1}")

print(f"The total time take :{et - st}")

arr1 :[ 1  2  3  4  5  6  7  8  9 10]
arr1 :[-1724114087 -1724114086 -1724114085 -1724114084 -1724114083 -1724114082
 -1724114081 -1724114080 -1724114079 -1724114078]
The total time take :0.06528663635253906


C:\Users\Kiran\AppData\Local\Temp\ipykernel_28236\4158236953.py:12: RuntimeWarning: overflow encountered in scalar add
  arr1[i] += (j ** 2)


In [33]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"arr1:{arr1}")

def get_square(x):
    if x < 0:
        return 0
    else:
        return x ** 2
    
vector_fun = np.vectorize(get_square)

result = vector_fun(arr1)

print(result)


arr1:[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   9  16  25  36  49  64  81 100]
