In [2]:
import numpy as np

# ndim attribute

arr1 = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

print(arr1)
print(arr1.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [4]:
# attribute size

arr1 = np.array([[1, 2, 3, 4,],
                 [5, 6, 7, 8]])

print(arr1)
print(arr1.size)

[[1 2 3 4]
 [5 6 7 8]]
8


In [7]:
# attribute shape

arr1 = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8]])

print(arr1)
print(arr1.shape)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [9]:
# attribute dtype

arr1 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8]])

print(arr1.dtype)
print(arr1)

int32
[[1 2 3 4]
 [5 6 7 8]]


In [11]:
# attribute itemsize

arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

print(arr1.itemsize)
print(arr1)

4
[[1 2 3 4]
 [5 6 7 8]]


In [12]:
# attribute data

arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

print(arr1.data)
print(arr1)


[[1 2 3 4]
 [5 6 7 8]]
