In [8]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(f"arr1 :{arr1}")

boolean_mask = arr1 > 6
print(f"Boolean  Mask :{arr1 > 5}")

boolean_mask = arr1 % 2 != 0
print(boolean_mask)

print(arr1[boolean_mask])

arr1 :[ 1  2  3  4  5  6  7  8  9 10]
Boolean  Mask :[False False False False False  True  True  True  True  True]
[ True False  True False  True False  True False  True False]
[1 3 5 7 9]


arr1 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 32, 47, 51])
print(F

In [13]:
arr1 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 32, 47, 51])

print(f"arr1 :{arr1}")

boolean_mask = (arr1 < 10) | (arr1 > 40)

result = arr1[boolean_mask]

print(result)

arr1 :[ 1  2  4  9 11 16 18 22 26 31 32 47 51]
[ 1  2  4  9 47 51]


In [16]:
# modfying array using boolean indexing

arr1 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 32, 47, 51, 52])
print(f"arr1 :{arr1}")

arr2 = arr1.copy()          # deep copy

# change all even number to 0 
arr2[arr1 % 2 == 0] = 0

print(f"arr2 :{arr2}")



arr1 :[ 1  2  4  9 11 16 18 22 26 31 32 47 51 52]
arr2 :[ 1  0  0  9 11  0  0  0  0 31  0 47 51  0]


In [22]:
# 2d indexing

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6], 
                 [7, 8, 9]])
print(f"arr1 :\n{arr1}")
# array elements that are greater than 3

boolean_mask = arr1 > 3

print("-" * 60)
result = arr1[boolean_mask]

print(result)

arr1 :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------------------------------------
[4 5 6 7 8 9]
