In [1]:
import numpy as np
import pandas as pd

In [4]:
# joining dataframes

DF1 = pd.DataFrame(
    {"key":["a", "b", "c", "c", "d", "e"], 
     "num1":range(6)})
DF2 = pd.DataFrame(
    {"key":["b", "c", "e","f"],
     "num2":range(4)})

In [5]:
print(DF1)

  key  num1
0   a     0
1   b     1
2   c     2
3   c     3
4   d     4
5   e     5


In [7]:
print(DF2)

  key  num2
0   b     0
1   c     1
2   e     2
3   f     3


In [10]:
DF3 = pd.merge(DF1, DF2, on="key")
print(DF3)

  key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2


In [18]:
DF4 = pd.DataFrame(
    {"key1":["a", "b", "c", "c", "d", "e"],
     "num1":range(6)})

DF5 = pd.DataFrame(
    {"key2":["b", "c", "e", "f"], 
    "num2":range(4)})

In [19]:
print(DF4)

  key1  num1
0    a     0
1    b     1
2    c     2
3    c     3
4    d     4
5    e     5


In [20]:
print(DF5)

  key2  num2
0    b     0
1    c     1
2    e     2
3    f     3


In [24]:
DF6 = pd.merge(DF4, DF5, left_on="key1", right_on="key2")
print(DF6)

  key1  num1 key2  num2
0    b     1    b     0
1    c     2    c     1
2    c     3    c     1
3    e     5    e     2


In [26]:
print(DF1)

  key  num1
0   a     0
1   b     1
2   c     2
3   c     3
4   d     4
5   e     5


In [27]:
print(DF2)

  key  num2
0   b     0
1   c     1
2   e     2
3   f     3


In [28]:
DF3 = pd.merge(DF1, DF2, how="outer")
print(DF3)

  key  num1  num2
0   a   0.0   NaN
1   b   1.0   0.0
2   c   2.0   1.0
3   c   3.0   1.0
4   d   4.0   NaN
5   e   5.0   2.0
6   f   NaN   3.0


In [31]:
DF3 = pd.merge(DF1, DF2, how="inner")
print(DF3)

  key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2


In [33]:
DF3 = pd.merge(DF1, DF2, how="right")
print(DF3)

  key  num1  num2
0   b   1.0     0
1   c   2.0     1
2   c   3.0     1
3   e   5.0     2
4   f   NaN     3


In [49]:
DF1 = pd.DataFrame({
    "letter":["a", "a", "b", "b", "a", "c"],
    "num":range(6)})
DF2 = pd.DataFrame({
    "value":[3, 5, 7]}, 
    index=["a", "b", "e"]
)

In [40]:
print(DF1)

  letter  num
0      a    0
1      a    1
2      b    2
3      b    3
4      a    4
5      c    5


In [50]:
print(DF2)

   value
a      3
b      5
e      7


In [51]:
DF3 = pd.merge(DF1, DF2, left_on="letter", right_index=True)
print(DF3)

  letter  num  value
0      a    0      3
1      a    1      3
4      a    4      3
2      b    2      5
3      b    3      5


In [52]:
# Merge these Dataframes how=outer by index
# Solve the problem

right=pd.DataFrame(
    [[1,2],[3,4],[5,6]],
    index=["a","c","d"],
    columns=["Tom","Tim"])

left=pd.DataFrame(
    [[7,8],[9,10],[11,12],[13,14]],
    index=["a","b","e","f"],
    columns=["Sam","Kim"])


In [54]:
seq= np.arange(20).reshape(4, 5)
print(seq)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [58]:
res = np.concatenate([seq, seq], axis = 1)
print(res)

[[ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]]


In [61]:
res = np.concatenate([seq, seq], axis=0)
print(res)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [63]:
data1 = pd.Series([0, 1], index=["a", "b"])
data2 = pd.Series([2, 3, 4], index=["c", "d", "e"])
data3 = pd.Series([5, 6], index=["f", "g"])

In [65]:
print(data1)

a    0
b    1
dtype: int64


In [67]:
print(data2)

c    2
d    3
e    4
dtype: int64


In [69]:
print(data3)

f    5
g    6
dtype: int64


In [73]:
res = pd.concat([data1, data2, data3])
print(res)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64


In [75]:
res = pd.concat([data1, data2, data3], axis=1)
print(res)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [77]:
data4 = pd.Series([10, 11, 12], 
                 index=["a", "b", "c"])
res = pd.concat([data1, data4], join="inner")
print(res)

a     0
b     1
a    10
b    11
c    12
dtype: int64


In [78]:
res = pd.concat([data1, data2, data4], 
               keys=["one", "two", "three"])
print(res)

one    a     0
       b     1
two    c     2
       d     3
       e     4
three  a    10
       b    11
       c    12
dtype: int64
